### ISSUE TITLE
AttributeError: 'Function' object has no attribute 'get_closest_marker'

### ISSUE THREAD

**Issue by gshif** [jlaska/pytest-github#24]
Have a question. I am running python 2.7.14 with pytest 3.0.7 on MAC
I am always seeing an error:
```
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytest_github/plugin.py", line 323, in pytest_itemcollected
INTERNALERROR>     marker = item.get_closest_marker('github')
INTERNALERROR> AttributeError: 'Function' object has no attribute 'get_closest_marker'
```

Any help would be greatly appreciated

**Comment by jlaska** [comment]
@kdelee Would you mind taking a look at this one?  Appears related to the recent `get_closest_marker` changes.

**Comment by gshif** [comment]
Hi @jlaska, @kdelee,
I just wanted to follow up on my original question whether you were able to take a look at the error.
Thanks.

**Comment by kdelee** [comment]
@gshif :wave: hey just now noticing this! Will take a look

**Comment by gshif** [comment]
Thanks @kdelee,

**Comment by kdelee** [comment]
sounds like this can get closed (I don't have power to do that)
